services:
  traceability:
    build: .
    image: energous_fvi
    container_name: energous_fvi
    ports:
      - "5050:5050"
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=production